In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
%matplotlib inline

In [9]:
data_master = pd.read_csv('data/Master.csv')
data_batting = pd.read_csv('data/Batting.csv')
data_salaries = pd.read_csv('data/Salaries.csv')

In [ ]:
data_master

In [ ]:
data_batting.head(2)

In [ ]:
data_salaries.head(2)

In [10]:
player_id_list = pd.merge(data_master, data_batting)

In [14]:
player_id_df = pd.merge(player_id_list,data_salaries)

In [ ]:
player_id_cpy.'salary'.groupby(ufo.index)

In [12]:
player_id_cpy = player_id_df.rename(columns={"playerID":"ID"}).copy()

In [17]:
player_id_cpy.drop_duplicates('salary')

,ID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,salary
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,300000
1,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387500
2,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,403250
3,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,419000
4,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2750000
5,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500000
6,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600000
7,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,625000
8,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,675000
9,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,400000
10,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,327000
11,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,418000
12,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,485000
13,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,525900
14,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087500
15,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,NaN,NaN,NaN,...,3.0,3.0,9.0,28.0,1.0,0.0,2.0,5.0,2.0,175000
16,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,NaN,NaN,NaN,...,1.0,1.0,5.0,12.0,0.0,0.0,1.0,1.0,4.0,255000
19,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68000
20,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185000
21,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357500
22,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1850000
23,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2350000
24,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2775000
26,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2200000
28,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,2.0,0.0,3.0,20.0,0.0,0.0,3.0,0.0,3.0,109000
30,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,4.0,3.0,36.0,110.0,4.0,5.0,2.0,5.0,6.0,119000
31,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,3.0,3.0,22.0,99.0,1.0,3.0,4.0,0.0,7.0,250000
32,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,3.0,1.0,14.0,68.0,3.0,1.0,6.0,0.0,5.0,650000
33,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,2.0,1.0,10.0,34.0,0.0,1.0,1.0,1.0,3.0,1000000
34,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,3.0,2.0,16.0,69.0,0.0,0.0,2.0,1.0,4.0,900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24201,woodsga01,1953.0,7.0,20.0,USA,CA,Santa Barbara,2015.0,2.0,19.0,...,0.0,1.0,14.0,18.0,0.0,0.0,1.0,0.0,2.0,321667
24210,woodtr01,1987.0,2.0,6.0,USA,AR,Little Rock,NaN,NaN,NaN,...,0.0,0.0,2.0,16.0,0.0,0.0,0.0,0.0,0.0,5686000
24249,worreto01,1959.0,9.0,28.0,USA,CA,Arcadia,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2416666
24264,wrighda03,1982.0,12.0,20.0,USA,VA,Norfolk,NaN,NaN,NaN,...,20.0,5.0,66.0,113.0,13.0,5.0,0.0,8.0,15.0,374000
24271,wrighda03,1982.0,12.0,20.0,USA,VA,Norfolk,NaN,NaN,NaN,...,17.0,3.0,55.0,79.0,5.0,5.0,0.0,2.0,11.0,10192071
24276,wrighja01,1974.0,12.0,24.0,USA,OK,Oklahoma City,NaN,NaN,NaN,...,0.0,0.0,3.0,22.0,0.0,0.0,3.0,0.0,1.0,169500
24293,wrighja02,1975.0,12.0,29.0,USA,CA,Anaheim,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2562500
24351,yeagest01,1948.0,11.0,24.0,USA,WV,Huntington,NaN,NaN,NaN,...,0.0,0.0,12.0,23.0,0.0,0.0,2.0,1.0,5.0,412809
24367,youklke01,1979.0,3.0,15.0,USA,OH,Cincinnati,NaN,NaN,NaN,...,0.0,1.0,14.0,19.0,0.0,2.0,0.0,0.0,0.0,323125
24368,youklke01,1979.0,3.0,15.0,USA,OH,Cincinnati,NaN,NaN,NaN,...,5.0,2.0,91.0,120.0,0.0,9.0,0.0,11.0,12.0,354600
24377,youmafl01,1964.0,5.0,11.0,USA,FL,Tampa,NaN,NaN,NaN,...,0.0,0.0,0.0,16.0,0.0,0.0,1.0,0.0,0.0,91500
24399,youngch04,1983.0,9.0,5.0,USA,TX,Houston,NaN,NaN,NaN,...,10.0,3.0,36.0,93.0,3.0,2.0,0.0,2.0,7.0,8700000
24406,youngcu01,1960.0,4.0,16.0,USA,MI,Saginaw,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,171875
24416,youngde03,1985.0,9.0,14.0,USA,AL,Birmingham,NaN,NaN,NaN,...,2.0,5.0,12.0,92.0,1.0,4.0,0.0,5.0,17.0,1152000
24423,youngde04,1982.0,6.0,30.0,USA,CA,Los Angeles,NaN,NaN,NaN,...,1.0,0.0,13.0,52.0,0.0,1.0,1.0,1.0,5.0,444500
24487,youngma01,1958.0,8.0,9.0,USA,CA,Pasadena,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,587000
24502,youngmi02,1976.0,10.0,19.0,USA,CA,Covina,NaN,NaN,NaN,...,10.0,0.0,55.0,109.0,0.0,2.0,0.0,6.0,19.0,6174974
24503,youngmi02,1976.0,10.0,19.0,USA,CA,Covina,NaN,NaN,NaN,...,8.0,3.0,47.0,90.0,2.0,1.0,0.0,4.0,16.0,13054526
24504,youngmi02,1976.0,10.0,19.0,USA,CA,Covina,NaN,NaN,NaN,...,4.0,2.0,50.0,115.0,4.0,1.0,0.0,11.0,21.0,13174974
24505,youngmi02,1976.0,10.0,19.0,USA,CA,Covina,NaN,NaN,NaN,...,6.0,2.0,47.0,78.0,7.0,2.0,0.0,9.0,17.0,16174974
24507,youngmi02,1976.0,10.0,19.0,USA,CA,Covina,NaN,NaN,NaN,...,1.0,0.0,42.0,78.0,4.0,1.0,0.0,1.0,18.0,18374975
24520,zambrca01,1981.0,6.0,1.0,Venezuela,Carabobo,Puerto Cabello,NaN,NaN,NaN,...,0.0,0.0,0.0,25.0,0.0,0.0,4.0,0.0,2.0,3760000
24524,zambrca01,1981.0,6.0,1.0,Venezuela,Carabobo,Puerto Cabello,NaN,NaN,NaN,...,0.0,0.0,1.0,28.0,0.0,0.0,1.0,1.0,0.0,18750000
24525,zambrca01,1981.0,6.0,1.0,Venezuela,Carabobo,Puerto Cabello,NaN,NaN,NaN,...,0.0,0.0,2.0,15.0,0.0,0.0,2.0,1.0,0.0,18875000
24586,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,NaN,NaN,NaN,...,3.0,1.0,41.0,73.0,4.0,1.0,0.0,3.0,14.0,9025000
24596,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,NaN,NaN,NaN,...,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,7900000
24606,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,...,17.0,6.0,91.0,104.0,4.0,2.0,1.0,4.0,7.0,415900
24608,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,...,19.0,6.0,77.0,128.0,1.0,2.0,2.0,5.0,9.0,4687300
24610,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,...,11.0,3.0,72.0,91.0,4.0,7.0,1.0,6.0,18.0,5687300
24621,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,NaN,NaN,NaN,...,0.0,3.0,17.0,158.0,1.0,17.0,0.0,4.0,12.0,504100

In [ ]:
player_id_cpy

In [ ]:
player_id_cpy = player_id_df.rename(columns={"playerID":"ID"}).copy()